package UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Ultils.Auth;
import Ultils.MsgBox;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

public class mainFrame extends javax.swing.JFrame {

    public mainFrame() {
        initComponents();
        init();
    }

    void init() {
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        new Timer(1000, new ActionListener() {
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(sdf.format(new Date()));
            }
        }).start();
        new ChaoJDialog(this, true).setVisible(true);

    }

    public void OpenFrameAnother(JInternalFrame x) {
        for (JInternalFrame frmChild : mainFrame.getAllFrames()) {
            frmChild.dispose();
        }

        x.setLocation(this.getWidth() / 2 - x.getWidth() / 2,
                (this.getHeight() - 20) / 2 - x.getHeight() / 2 - 60);
        mainFrame.add(x);
        x.setVisible(true);
    }

    // Open Form 
    void openLogin() {
        new dangNhapJDialog(this, true).setVisible(true);
    }

    void OpenchangePassWord() {
        if (Auth.isLogin()) {
            new doiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập");
        }

    }
//
//    void LogOut() {
//
//        if (MsgBox.confirm(this, "Bạn Muốn Đăng Xuất ?")) {
//            Auth auth = new Auth();
//            auth.clear();
//            MsgBox.alert(this, "Bạn Đăng Xuất Thành Công");
//        }
//    }
//

    void OpenDatPhong() {
        DatPhongJInternalFrame datphong = new DatPhongJInternalFrame();
        OpenFrameAnother(datphong);
    }
//

    void OpenSanPham() {
        SanPhamJInternalFrame sp = new SanPhamJInternalFrame();
        OpenFrameAnother(sp);
    }

    void OpenPhong() {
//        if (Auth.isLogin()) {
//            PhongJInternalFrame phong = new PhongJInternalFrame();
//            OpenFrameAnother(phong);
//        } else {
//            MsgBox.alert(this, "Vui Lòng Đăng Nhập");
//        }
//        
        PhongJInternalFrame phong = new PhongJInternalFrame();
        OpenFrameAnother(phong);
    }

    void OpenNhanVien() {
        if (Auth.isLogin()) {
            nhanVienJInternalFrame nhanvien = new nhanVienJInternalFrame();
            OpenFrameAnother(nhanvien);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        mainFrame = new javax.swing.JDesktopPane(){
            //    protected void  paintComponent (Graphics g){
                //        Image img = new ImageIcon(this.getClass().getResource("/icon/logo.png")).getImage();
                //        try {
                    //            Graphics g2d = (Graphics2D)g;
                    //            double x= img.getWidth(null);
                    //            double y= img.getHeight(null);
                    //            //g2d.scale(getWidth()/x,getHeight()/y);
                    //            //g2d.drawImage(img, 0, 0, this);
                    //            g2d.drawImage(img, this.getWidth()/4+100,this.getHeight()/4-100,this);
                    //        } catch (Exception e) {
                    //            System.out.println("Gap loi");
                    //        }
                //    }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        menuSanPham = new javax.swing.JMenu();
        mniPhong = new javax.swing.JMenuItem();
        mniDatPhong = new javax.swing.JMenuItem();
        mniSanPham = new javax.swing.JMenuItem();
        mniQuanLyNhanVien = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        mniLuongNguoiHoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();

        jMenuItem15.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jMenuItem15.setText("CHÚC BẠN HỌC TẬP TỐT");
        jMenuItem15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        popupMenu.add(jMenuItem15);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");

        mainFrame.setBackground(new java.awt.Color(157, 189, 228));
        mainFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainFrameMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        getContentPane().add(mainFrame, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Hệ quản lý đào tạo");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        lblDongHo.setForeground(new java.awt.Color(0, 51, 255));
        lblDongHo.setText("10:55 PM");
        jPanel1.add(lblDongHo, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        menuBar.add(mnuHeThong);

        menuSanPham.setText("Quản lý");
        menuSanPham.setMargin(new java.awt.Insets(5, 5, 5, 5));
        menuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSanPhamActionPerformed(evt);
            }
        });

        mniPhong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPhong.setText("Phòng ");
        mniPhong.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhongActionPerformed(evt);
            }
        });
        menuSanPham.add(mniPhong);

        mniDatPhong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDatPhong.setText("Đặt Phòng");
        mniDatPhong.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongActionPerformed(evt);
            }
        });
        menuSanPham.add(mniDatPhong);

        mniSanPham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSanPham.setText("Sản Phẩm");
        mniSanPham.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSanPhamActionPerformed(evt);
            }
        });
        menuSanPham.add(mniSanPham);

        mniQuanLyNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQuanLyNhanVien.setText("Quản lý nhân viên");
        mniQuanLyNhanVien.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyNhanVienActionPerformed(evt);
            }
        });
        menuSanPham.add(mniQuanLyNhanVien);

        menuBar.add(menuSanPham);

        menuThongKe.setText("Thống kê");
        menuThongKe.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mniLuongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniLuongNguoiHoc.setText("Thống Kê");
        mniLuongNguoiHoc.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mniLuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongNguoiHocActionPerformed(evt);
            }
        });
        menuThongKe.add(mniLuongNguoiHoc);
        menuThongKe.add(jSeparator3);
        menuThongKe.add(jSeparator4);

        menuBar.add(menuThongKe);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongActionPerformed
        OpenDatPhong();
    }//GEN-LAST:event_mniDatPhongActionPerformed


    private void mniPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhongActionPerformed
        OpenPhong();
    }//GEN-LAST:event_mniPhongActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        openLogin();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSanPhamActionPerformed
        OpenSanPham();
    }//GEN-LAST:event_mniSanPhamActionPerformed

    private void mniQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyNhanVienActionPerformed
        OpenNhanVien();
    }//GEN-LAST:event_mniQuanLyNhanVienActionPerformed

    private void mniLuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongNguoiHocActionPerformed

    }//GEN-LAST:event_mniLuongNguoiHocActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        OpenchangePassWord();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mainFrameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFrameMouseReleased

    }//GEN-LAST:event_mainFrameMouseReleased

    private void menuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSanPhamActionPerformed
        OpenSanPham();
    }//GEN-LAST:event_menuSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JDesktopPane mainFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuSanPham;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDatPhong;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLuongNguoiHoc;
    private javax.swing.JMenuItem mniPhong;
    private javax.swing.JMenuItem mniQuanLyNhanVien;
    private javax.swing.JMenuItem mniSanPham;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
