/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DonViTinhDAO;
import DAO.SanPhamDAO;

import Entity.DonViTinh;
import Entity.SanPham;
import Ultils.Auth;
import Ultils.MsgBox;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOW
 */
public class SanPhamJinternal extends javax.swing.JInternalFrame {

    DefaultTableModel model;

    public SanPhamJinternal() {
        initComponents();
        setModelTable();
        fillComboBoxChuyenDe();
        FillTable();
        updateStatus();
    }

    public static void refresh() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDVT.getModel();
        model.removeAllElements();
        DonViTinhDAO cdDAO = new DonViTinhDAO();
        List<DonViTinh> list = cdDAO.selectAll();
        for (DonViTinh DVT : list) {
            model.addElement(DVT);
        }
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"ID Sản Phẩm", "Tên Sản Phẩm", "Giá Sản Phẩm", "Đơn Vị Tính", "Người Tạo"});
        tblSP.setModel(model);
    }

    public void fillComboBoxChuyenDe() {

        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDVT.getModel();
        model.removeAllElements();
        List<DonViTinh> list = DAO.selectAll();
        for (DonViTinh DVT : list) {
            model.addElement(DVT);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        pnlCongCuBangKhoaHoc = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnlFormKhoaHoc = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtIDNhanVien = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtIDSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtGiaSP = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        pnlNgayKhaiGiang = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cboDVT = new javax.swing.JComboBox<>();
        txtTimKiemSP = new javax.swing.JTextField();

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Sản Phẩm");

        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblSP.setAutoCreateRowSorter(true);
        tblSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSP.setGridColor(new java.awt.Color(255, 255, 255));
        tblSP.setRowHeight(30);
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSPMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tblSP);

        pnlCongCuBangKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlCongCuBangKhoaHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(102, 102, 102));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 20));

        btnFirst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(102, 102, 102));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 10, 40, 20));

        btnPrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 102, 102));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 20));

        btnNext.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, 20));

        pnlFormKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormKhoaHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Người Tạo");
        pnlFormKhoaHoc.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        txtIDNhanVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtIDNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 320, 30));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("ID Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Ghi chú");
        pnlFormKhoaHoc.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Giá Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        txtIDSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtIDSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 320, 30));

        txtTenSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 320, 30));

        txtGiaSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtGiaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 320, 30));

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Tên Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane9.setViewportView(txtGhiChu);

        pnlFormKhoaHoc.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 830, 110));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 102, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(102, 102, 102));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(102, 102, 102));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        pnlNgayKhaiGiang.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgayKhaiGiang.setLayout(new java.awt.BorderLayout());
        pnlFormKhoaHoc.add(pnlNgayKhaiGiang, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 50, 30));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Dơn Vị TÍnh");

        cboDVT.setFont(new java.awt.Font("SansSerif", 1, 14));
        cboDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDVTActionPerformed(evt);
            }
        });

        txtTimKiemSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimKiemSP.setForeground(new java.awt.Color(153, 153, 153));
        txtTimKiemSP.setText("Tìm kiếm Sản Phẩm");
        txtTimKiemSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemSPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemSPFocusLost(evt);
            }
        });
        txtTimKiemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSPActionPerformed(evt);
            }
        });
        txtTimKiemSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(cboDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCongCuBangKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(550, 550, 550)
                            .addComponent(jLabel27))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlFormKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cboDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addComponent(pnlCongCuBangKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addComponent(pnlFormKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMousePressed
        // TODO add your handling code here:
        row = tblSP.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblSPMousePressed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        insert();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        fillComboBoxChuyenDe();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:

        update();

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void cboDVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDVTActionPerformed
        // TODO add your handling code here:
        FillTable();
    }//GEN-LAST:event_cboDVTActionPerformed

    private void txtTimKiemSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemSPFocusGained
        // TODO add your handling code here:
        //        focusGained();
    }//GEN-LAST:event_txtTimKiemSPFocusGained

    private void txtTimKiemSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemSPFocusLost
        // TODO add your handling code here:
        //        focusLost();
    }//GEN-LAST:event_txtTimKiemSPFocusLost

    private void txtTimKiemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSPActionPerformed

    private void txtTimKiemSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSPKeyReleased
        // TODO add your handling code here:
        //        fillTable();
    }//GEN-LAST:event_txtTimKiemSPKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    public static javax.swing.JComboBox<String> cboDVT;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlCongCuBangKhoaHoc;
    private javax.swing.JPanel pnlFormKhoaHoc;
    private javax.swing.JPanel pnlNgayKhaiGiang;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtIDNhanVien;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtTenSP;
    private static javax.swing.JTextField txtTimKiemSP;
    // End of variables declaration//GEN-END:variables
  int row = -1;
    DonViTinhDAO DAO = new DonViTinhDAO();
    SanPhamDAO SPDAO = new SanPhamDAO();

    public void setForm(SanPham SP) {
        DonViTinh donViTinh = (DonViTinh) cboDVT.getSelectedItem();
        txtIDSP.setText(String.valueOf((long) SP.getIdSanPham()));
        txtTenSP.setText(SP.getTenSanPham());
        txtGiaSP.setText(String.valueOf(SP.getGiaSanPham()));
        txtIDNhanVien.setText(SP.getIdNhanVien());
        txtGhiChu.setText(SP.getMoTaSanPham());
    }

    public SanPham getForm() {
        SanPham SP = new SanPham();
        SP.setIdSanPham(SP.getIdSanPham());
        SP.setTenSanPham(SP.getTenSanPham());
        SP.setGiaSanPham(Integer.valueOf(SP.getGiaSanPham()));
        SP.setIdNhanVien(Auth.user.getHoTen());
        return SP;
    }

    public void clearForm() {
        row = -1;
        txtTenSP.setText("");
        txtGiaSP.setText("");
        txtGhiChu.setText("");
        updateStatus();
    }

    public void edit() {
        int maKH = Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0)));
        SanPham SP = SPDAO.selectById(maKH);
        updateStatus();
    }

    public void insert() {
        SanPham SP = getForm();
        try {
            SPDAO.insert(SP);
            clearForm();
            FillTable();
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    public void update() {
        SanPham SP = SPDAO.selectById(Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0))));
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật không?") == true) {
            try {

                //System.out.println(kh.getMaKH());
                SPDAO.update(SP);
                clearForm();
                FillTable();
                MsgBox.alert(this, "Cập nhật thành côgn!");
            } catch (Exception e) {
                Logger.getLogger(SanPhamDAO.class.getName()).log(Level.SEVERE, null, e);
                MsgBox.alert(this, "Không thể xóa!");
            }

        }
    }

    public void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa !");
        } else {
            int makh = Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0)));

            if (MsgBox.confirm(this, "Bạn có chắc muốn xóa không?")) {
                try {
                    SPDAO.delete(makh);
                    FillTable();
                    clearForm();
                    //MsgBox.alert(this, "Xóa khóa học thành công!");
                } catch (Exception e) {
                    Logger.getLogger(SanPhamDAO.class.getName()).log(Level.SEVERE, null, e);
                    MsgBox.alert(this, "Không thể xóa !");
                    e.printStackTrace();
                }
            }
        }
    }

    public void first() {
        row = 0;
        tblSP.setRowSelectionInterval(row, row);
        edit();
    }

    public void prev() {
        if (row > 0) {
            row--;
            tblSP.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void next() {
        if (row < tblSP.getRowCount() - 1) {
            row++;
            tblSP.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void last() {
        row = tblSP.getRowCount() - 1;
        tblSP.setRowSelectionInterval(row, row);
        edit();
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblSP.getRowCount() - 1);
        DonViTinh DVT = (DonViTinh) cboDVT.getSelectedItem();
        txtDVT.setEditable(false);
        txtIDNhanVien.setEditable(false);
        txtDVT.setText(DVT.getTenDVT());
        txtDVT.setText(String.valueOf((long) DVT.getIDDVT()));
        txtIDNhanVien.setText(Auth.user.getIdNhanVien());

        btnThem.setEnabled(!edit);
        btnCapNhat.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    public void FillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        try {
            DonViTinh DVT = (DonViTinh) cboDVT.getSelectedItem();
            List<SanPham> list;
            list = SPDAO.selectByChuyenDe(String.valueOf(DVT.getIDDVT()));
            for (SanPham SP : list) {
                model.addRow(new Object[]{SP.getIdSanPham(), SP.getTenSanPham(), SP.getGiaSanPham(), SP.getIdNhanVien(), SP.getTenSanPham()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void chonChuyenDe() {
        DonViTinh DVT = (DonViTinh) cboDVT.getSelectedItem();
        txtDVT.setText(String.valueOf(DVT.getTenDVT()));
        FillTable();
        row = -1;
    }

}
