/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DonViTinhDAO;
import DAO.SanPhamDAO;
import Entity.DonViTinh;
import Entity.SanPham;
import Ultils.Auth;
import Ultils.MsgBox;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOW
 */
public class SanPhamJrame extends javax.swing.JFrame {

    /**
     * Creates new form SanPhamJrame
     */
    public SanPhamJrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        pnlCongCuBangKhoaHoc = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnlFormKhoaHoc = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtDVT = new javax.swing.JTextField();
        txtIDSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtNGTAO = new javax.swing.JTextField();
        txtGiaSP = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        pnlNgayKhaiGiang = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cboDTV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Sản Phẩm");

        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblSP.setAutoCreateRowSorter(true);
        tblSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSP.setGridColor(new java.awt.Color(255, 255, 255));
        tblSP.setRowHeight(30);
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSPMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tblSP);

        pnlCongCuBangKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlCongCuBangKhoaHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(102, 102, 102));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        btnFirst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(102, 102, 102));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        btnPrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 102, 102));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        btnNext.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCongCuBangKhoaHoc.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        pnlFormKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormKhoaHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Đơn Vị Tính");
        pnlFormKhoaHoc.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("ID Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 20));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Ghi chú");
        pnlFormKhoaHoc.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Giá Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel35.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Người Nhập");
        pnlFormKhoaHoc.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        txtDVT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtDVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 320, 30));

        txtIDSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtIDSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 320, 30));

        txtTenSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 320, 30));

        txtNGTAO.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtNGTAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 320, 30));

        txtGiaSP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormKhoaHoc.add(txtGiaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 320, 30));

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Tên Sản Phẩm");
        pnlFormKhoaHoc.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane9.setViewportView(txtGhiChu);

        pnlFormKhoaHoc.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 830, 110));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 102, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(102, 102, 102));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(102, 102, 102));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlFormKhoaHoc.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        pnlNgayKhaiGiang.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgayKhaiGiang.setLayout(new java.awt.BorderLayout());
        pnlFormKhoaHoc.add(pnlNgayKhaiGiang, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 50, 30));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Đơn Vị Tính");

        cboDTV.setFont(new java.awt.Font("SansSerif", 1, 14));
        cboDTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(550, 550, 550)
                            .addComponent(jLabel27))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel29)
                            .addGap(5, 5, 5)
                            .addComponent(cboDTV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlCongCuBangKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(pnlFormKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addComponent(cboDTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pnlCongCuBangKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 350, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMousePressed
        // TODO add your handling code here:
        row = tblSP.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblSPMousePressed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
            insert();
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        fillComboBoxChuyenDe();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
       
            update();
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void cboDTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDTVActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_cboDTVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamJrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    public static javax.swing.JComboBox<String> cboDTV;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlCongCuBangKhoaHoc;
    private javax.swing.JPanel pnlFormKhoaHoc;
    private javax.swing.JPanel pnlNgayKhaiGiang;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtNGTAO;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables

 SanPhamDAO khoaHocDAO = new SanPhamDAO();
    DonViTinhDAO chuyenDeDAO = new DonViTinhDAO();
    int row = -1;

    public void setForm(SanPham SP) {
        DonViTinh DVT = (DonViTinh) cboDTV.getSelectedItem();
        txtDVT.setText(DVT.getTenDVT());
        txtIDSP.setText(String.valueOf(SP.getIdSanPham()));
        txtTenSP.setText(SP.getTenSanPham());
        txtGiaSP.setText(String.valueOf(SP.getGiaSanPham()));
        txtNGTAO.setText(SP.getIdNhanVien());
    }

    public SanPham getForm() {
        SanPham SP = new SanPham();
        DonViTinh DVT = (DonViTinh) cboDTV.getSelectedItem();
//       SP.setDVT(DVT.getIDDVT());
       SP.setIdSanPham(Integer.valueOf(txtIDSP.getText()));
       SP.setTenSanPham(txtTenSP.getText());
       SP.setGiaSanPham(Integer.valueOf(txtGiaSP.getText()));
       SP.setIdNhanVien(Auth.user.getIdNhanVien());
       return SP;
    }

    public void clearForm() {
        row = -1;
        txtIDSP.setText("");
        txtTenSP.setText("");
        txtGiaSP.setText("");
        txtGhiChu.setText("");
        updateStatus();
    }

    public void edit() {
        int maKH = Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0)));
        SanPham kh = khoaHocDAO.selectById(maKH);
        setForm(kh);
        updateStatus();
    }

    public void insert() {
        SanPham kh = getForm();
        try {
            khoaHocDAO.insert(kh);
            clearForm();
            fillTable();
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    public void update() {
        SanPham kh = khoaHocDAO.selectById(Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0))));
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật khóa học này không?") == true) {
            try {
                //System.out.println(kh.getMaKH());
                khoaHocDAO.update(kh);
                clearForm();
                fillTable();
                 MsgBox.alert(this, "Cập nhật thành côgn!");
            } catch (Exception e) {
                Logger.getLogger(SanPhamDAO.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }

    public void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa khóa học!");
        } else {
            int makh = Integer.parseInt(String.valueOf(tblSP.getValueAt(row, 0)));

            if (MsgBox.confirm(this, "Bạn có chắc muốn xóa khóa học này không?")) {
                try {
                    khoaHocDAO.delete(makh);
                    fillTable();
                    clearForm();
                    //MsgBox.alert(this, "Xóa khóa học thành công!");
                } catch (Exception e) {
                    Logger.getLogger(SanPhamDAO.class.getName()).log(Level.SEVERE, null, e);
                    MsgBox.alert(this, "Không thể xóa khóa học đã tồn tại học viên!");
                }
            }
        }
    }

    public void first() {
        row = 0;
        tblSP.setRowSelectionInterval(row, row);
        edit();
    }

    public void prev() {
        if (row > 0) {
            row--;
            tblSP.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void next() {
        if (row < tblSP.getRowCount() - 1) {
            row++;
            tblSP.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void last() {
        row = tblSP.getRowCount() - 1;
        tblSP.setRowSelectionInterval(row, row);
        edit();
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblSP.getRowCount() - 1);
        DonViTinh DVT = (DonViTinh) cboDTV.getSelectedItem();
        txtDVT.setEditable(false);
        txtIDSP.setEditable(false);
        txtTenSP.setEditable(false);
        txtGiaSP.setEditable(false);
        txtNGTAO.setEditable(false);
        txtDVT.setText(DVT.getTenDVT());    
        txtNGTAO.setText(Auth.user.getIdNhanVien());
        

        btnThem.setEnabled(!edit);
        btnCapNhat.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

    }

    public void fillComboBoxChuyenDe() {
        //Dùng để đổ dữ liệu vào cboChuyenDe_KhoaHoc 
//        new Thread(new Runnable() {
//            @Override
//            public void run() {
//                while (true) {
//                    try {
        //Thread.sleep(3000);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDTV.getModel();
        model.removeAllElements();
        List<DonViTinh> list = chuyenDeDAO.selectAll();
        for (DonViTinh cd : list) {
            model.addElement(cd);
        }
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(PanelQuanLyKhoaHoc.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//        }).start();
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        try {
            DonViTinh DVT = (DonViTinh) cboDTV.getSelectedItem();
            SanPhamDAO dao = new SanPhamDAO();
//            List<SanPham> list = dao.selectByChuyenDe(DVT.getIDDVT());
//            for (SanPham SP : list) {
//                model.addRow(new Object[]{
//                    SP.getDVT(),
//                    SP.getIdSanPham(),
//                    SP.getTenSanPham(),
//                    SP.getGiaSanPham(),
//                    SP.getIdNhanVien(),
//                    SP.getMoTaSanPham()});
//            }
        } catch (Exception e) {
        }
    }

    public void chonChuyenDe() {
        DonViTinh DVT = (DonViTinh) cboDTV.getSelectedItem();
        fillTable();
        row = -1;
    }
}
